In [15]:
#numpy gives us multi dimensional arrays
#it is fast compared to list
#advantages of numpy
"""
->less memory consumption
->faster than lists
->easier to use
"""
import numpy as np


In [16]:
x=np.array([1,2,3,4,5,7,8,9,10])
print(x)
print(type(x))

[ 1  2  3  4  5  7  8  9 10]
<class 'numpy.ndarray'>


In [17]:
y=[1,2,3,4,5,6,7,8,9,10]
print(y)
print(type(y))
#numpy arrays was seperated with spaces whereas list is seperated by commas


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


In [19]:
#difference between list and numpy
"""
data type storage->list can have diff data types in a single list.
numpy has majorly singular data type. we can do merge them but we generally maintain a singular data type.

NUMERICAL OPERATIONS-> List has limited efficiency compared to numpy.
it acta as a matrix so more operations possible.

can be made into multidimensional arrays.


List takes more memory comapred to numpy.

Easier to use for a big data.
"""

#time difference between creation of numpy and normal arrays using timeit() method
%timeit [j**4 for j in range(1,9)] #took 597ns
#arange()-> creates an array beyween the given range
%timeit np.arange(1,9)**4



542 ns ± 34 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.11 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
#creation of numpy arrays
import numpy as np
a=np.array([1,2,3])
x=[1,2,3,4]
#converting x to array
y=np.array(x)

print(a)
print(y)
print(type(y))
y

[1 2 3]
[1 2 3 4]
<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [4]:
l=[]
for i in range(1,5):
    input_value=int(input("enter number"))
    l.append(input_value)
#we got data as string.so convert to integer in input()
print(np.array(l))

enter number 5
enter number 5
enter number 4
enter number 4


[5 5 4 4]


In [5]:
#types of arrays->1D,2D,3D........
#number of blocks->dimension
"""
[]->1d
[[]]->2d
[[[]]]->3d
"""
#ndim()->tells dimension of array
#number of data should be of same length in each sublist
y=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(y)
print(y.ndim) #->tells the dimension of array



#creating n dimension array
#ndim-> number of dimensions
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
#creation of numpy array using functions

In [ ]:
"""array filled with 0's
array filled with 1's
creating an empty array
array with range of elements
diagonals filled with a particular number
array filled with a specified intervals
we can do all these things with numpy"""


In [31]:
#array with zeros
import numpy as np

arr_with_zeros=np.zeros(4)

#zero 2d array
arr_with_zero_twod=np.zeros((4,4))

print(arr_with_zeros)
print() #for a gap
print(arr_with_zero_twod)


#array with all ones
arr_with_all_ones=np.ones(5)
print(arr_with_all_ones)

print() #for a gap
#creation of empty array
arr_with_empty=np.empty(5)
print(f"empty array is {arr_with_empty}") #but we might not see it empty bcoz agar usse pahle koi bana hua hoga array toh usme vhi data aa jata hai

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]

empty array is [1. 1. 1. 1. 1.]


In [22]:
empty_array=np.empty((8,7))

empty_array2=np.empty(5)
print(empty_array)


print(empty_array2)

[[7.52590993e-312 7.52626763e-312 0.00000000e+000 6.95202422e-310
  2.51973479e-322 7.52646034e-312 7.52654956e-312]
 [7.52654956e-312 7.52646073e-312 7.52646073e-312 7.52646075e-312
  7.52646075e-312 7.52646075e-312 7.52654956e-312]
 [7.52646074e-312 7.52654956e-312 7.52654956e-312 7.52646074e-312
  7.52654956e-312 7.52646076e-312 7.52646075e-312]
 [7.52654956e-312 7.52646075e-312 7.52654957e-312 7.52654957e-312
  7.52646074e-312 7.52646074e-312 7.52654957e-312]
 [7.52646077e-312 7.52654957e-312 7.52646077e-312 7.52646077e-312
  7.52646076e-312 7.52646076e-312 7.52646074e-312]
 [7.52654957e-312 7.52646076e-312 7.52646135e-312 7.52646138e-312
  7.52646136e-312 7.52646137e-312 7.52646138e-312]
 [7.52646138e-312 7.52646138e-312 7.52654957e-312 7.52654957e-312
  7.52654957e-312 7.52646138e-312 7.52654957e-312]
 [7.52646139e-312 7.52646139e-312 7.52646139e-312 7.52646139e-312
  7.52646139e-312 7.52646139e-312 7.52654957e-312]]
[1. 1. 1. 1. 1.]


In [ ]:
#array with values in a range

In [25]:
arr_from_25_to_80=np.arange(25,81) #gives values from 25 to 80
print(arr_from_25_to_80)

[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80]


In [33]:
#diagonal arrays -> we use eye() method
"""
[1 0 0
 0 1 0
 0 0 1]
"""
dig_array=np.eye(3)
print(dig_array)

diag_array=np.eye(3,5) #create a 3*5 array and fill its diagonal with one
print(diag_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [41]:
#array with a special interval. we use linspace()
arr_linspace=np.linspace(0,10,num=5) #1 se 10 tk aise 5 number do jinme gap same ho.
arr_linsapce2=np.linspace(0,20,num=5)
print(f"{arr_linspace}    {arr_linsapce2}")

[ 0.   2.5  5.   7.5 10. ]    [ 0.  5. 10. 15. 20.]


In [43]:
#operations using numpy
#random generation of array with random numbers
"""
rand()-> random number between 0 and 1
randn()-> generates a value close to zero. This may return positive or negative numbers as well
ranf()-> gives an arrya of specified shapes and fills it with random floats in interval[0.0,1.0)
randint()-> Used for generation of a random number between a given range
"""
import numpy as np

In [60]:
#rand()-> works on rnadom() module so always add np.random......
rand_nums=np.random.rand(10) #a 1d array with 10 values will be generated.
print(rand_nums) #10 random vlaues between 0 and 1 


#mutli dimension random array
var1=np.random.rand(2,5) #a 2*5 dda formed with random values
print(var1)

#randn()-> close to zero numbers will be generated. it can also give negative numbers. WHEREAS RAND ONLY GAVE POSITIVE NUMBERS
var2=np.random.randn(5)
print(var2)

#ranf()-> gives a number between 0 and 1 excluding 1
nums=np.random.ranf(4)
print(nums)

#randint()-> gives random number between a user defined range
random_range=np.random.randint(4,10,5) #(min vlaue,max value, total numbers to be genrated)
print(random_range)

[0.42576468 0.42072283 0.88961645 0.55559087 0.90064387 0.69829165
 0.02111377 0.19946304 0.76345756 0.67911185]
[[0.99016716 0.82861406 0.71112039 0.81774366 0.70314198]
 [0.42755442 0.6534374  0.4205814  0.92886628 0.35454192]]
[ 0.74361023 -0.46266155  0.6187589   1.80048344 -1.67567386]
[0.18126295 0.73346963 0.19095065 0.49787263]
[8 4 7 8 9]


In [ ]:
#datatypes in numpy

In [70]:
#boolean,int,intc,intp,int8,int16,int32,int64,uint8....,float,complex,....
import numpy as np
var=np.array([1,2,3,4])
print(f"type of data type is {var.dtype}")

float_type=np.array([1.2,2.2,3.2,5])
print(f"the data type of array is {float_type.dtype}")

str_type=np.array(["Ashutosh","ASHU","HELLO"]) #<U8
print(f"the data type is {str_type.dtype}")

mixed_data=np.array([1,2,3,4,5,"ASHUTOSH","TIWARI"])
print(f"the data type is {mixed_data.dtype}") #<U11



type of data type is int32
the data type of array is float64
the data type is <U8
the data type is <U11


In [80]:
#conversion from one datatype to other
new_array=np.array([1,2,3,4])
print(new_array.dtype) #tells datatype of array->here int32
#lets convert int32 to int8
new_array2=np.array([1,2,3,4],dtype=np.int8) #converted from int32 to int8
print(new_array2.dtype)
new_array2=np.array([1,2,3,4],dtype=np.cdouble) #converted from int32 to complex128
print(new_array2.dtype)


#another method to convert from one datatype to another
x=np.array([1,2,3,4,5])
y=np.cdouble(x) #complex datatype
print(y," ",y.dtype)



#another method using astype()
c=np.array([1,2,3,4,5,6,7,8,9,10])
d=c.astype(float)
print(d)

int32
int8
complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]   complex128
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [109]:
#ARITHMETIC OPERATIONS
#addition of arrays np.add(a,b)
#subtraction of arrays np.subtract(a,b)
#multiplication of arrays np.multiply(a,b)
#division of arrays np.divide(a,b)
#modulus np.mod(%b)
#power np.power(a,b)
#reciprocal np.reciprocal(a)

#addition
arr=np.array([4,5,6,7,8,9])
print(arr+1)


arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([10,20,30,40,50,60,70])
addition:list=np.add(arr1,arr2)
#alternative->addition=arr1+arr2
print(addition)

#subtraction
#subtract:int=arr1-arr2
#print(subtract) alternative
ans:list=np.subtract(arr1,arr2)
print(ans)

#multiplication
arr=np.array([1,2,3,4,5])
m=arr*10
print(m)

#using multiply()
answer=np.multiply(arr,10)
print(f"ANSWER BY INBULIT METHOD {answer}")

#divion
arr2=np.array([1,2,3,4,5])
m=arr2/10
print(m)

#using divide()
ans_divide=np.divide(arr,10)
print(f"ANSWER BY INBUILT METHOD {ans_divide}")

#modulus
arr3=np.array([1,2,3,4,5])
m=arr3%5
print(m)

arr4=np.array([1,2,3,4,5])
ans_mod=np.mod(arr4,5)
print(f"the answer of mod using numpy is {ans_mod}")

#recipocal
recipocal_ans=np.reciprocal(arr4)
print(f"the reciprocal of array is {recipocal_ans}")

#creating a multidimensional array and doing arithmetic operation on it
doubdimarr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
doubdimarr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
multi_2d=doubdimarr1*doubdimarr2
print(multi_2d)


#<-----------USING IN-BUILT METHODS FOR 2D ARRAYS------------------->
array_2D1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array_2D2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
addition_2d=np.add(array_2D1,array_2D2)
print(f"the addition is {addition_2d}")



[ 5  6  7  8  9 10]
[11 22 33 44 55 66 77]
[ -9 -18 -27 -36 -45 -54 -63]
[10 20 30 40 50]
ANSWER BY INBULIT METHOD [10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]
ANSWER BY INBUILT METHOD [0.1 0.2 0.3 0.4 0.5]
[1 2 3 4 0]
the answer of mod using numpy is [1 2 3 4 0]
the reciprocal of array is [1 0 0 0 0]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
the addition is [[12 14 16 18 20]
 [22 24 26 28 30]]


In [127]:
#ARTIHMETIC FUNCTIONS IN NUMPY
"""
np.min(x)
np.max(x)
np.argmin(x)
np.sqrt(x)
np.sin(x)
np.cos(x)
np.cumsum(x)
"""
import numpy as np
value=np.array([1,2,3,4,5,6,7,8,9,10])
print(f"maximum is {np.max(value)}")
print(f"minimum is {np.min(value)}")

#finding position at which min and max values are present
print(f"Minimum value is present at location {np.argmin(value)}")
print(f"Maximum value is present at location {np.argmax(value)}")


#applying on a 2d array
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"the maximum value in 2d array is {np.max(array_2d)} at position {np.argmax(array_2d)}")

#we can also find value about a axis
#if axis=0->column    axis=1->row

print(np.min(array_2d,axis=1)) #we got 1 4 7 har row se minimum value


#sqrt()
array5=np.array([[36,64,81],[25,36,49],[64,144,121]])
sqr=np.sqrt(array5)

print(f"the square root of each element of array is {sqr}")

#sin cos values
sin_matrix=np.array([1,2,3,4,5])
print(f"the sin values are {np.sin(sin_matrix)}")
print(f"the cos values are {np.cos(sin_matrix)}")


#cummulative sum-> [1 2 3]->[1(as it is)  3(2+1)   6(3+2+1)]

arr_new=np.array([1,2,3,4,5,6,7,8,9,10])
print(f"the cummulative sum is {np.cumsum(arr_new)}")  #helpful in stats

maximum is 10
minimum is 1
Minimum value is present at location 0
Maximum value is present at location 9
the maximum value in 2d array is 9 at position 8
[1 4 7]
the square root of each element of array is [[ 6.  8.  9.]
 [ 5.  6.  7.]
 [ 8. 12. 11.]]
the sin values are [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
the cos values are [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
the cummulative sum is [ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
#shaping and reshaping

In [10]:
#converting from one dimension to another dimension
"""
[[1 2]
 [1 2]] this is a 2*2 matrix
 """
import numpy as np

a=np.array([[1,2,3,4],[1,2,3,4]])

print(a)

#finding shape of array
print(a.shape) #2*4


b=np.array([1,2,3,4], ndmin=4) #makes a 4d array
print(b)
print(b.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)
[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [19]:
#reshaping from multi dimension to one dimension and vice versa
arr1=np.array([1,2,3,4,5,6])

x=arr1.reshape(3,2)    #kitti rows , kitte elements in one row
#here we needed 3 rows and 2 elements in each row
"""
1 2
3 4
5 6
"""
print(x)
#dimension of new array
print(x.ndim)     #number of brackets tell dimension


arr2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr2)
print(arr2.ndim)


c=arr2.reshape(2,3,2)
print(c)
print(c.ndim)


#3d array to 1d array
f=c.reshape(-1)  #c now back to one dimension array
print(f)


[[1 2]
 [3 4]
 [5 6]]
2
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
#BROADCASTING-> before operating 1)dimension should be same 2)kisi ek ke pass value same hona chahiye 
#it occurs during arithmetic operation of two arrays
import numpy as np
var1=np.array([1,2,3,4])
print(var1.shape)
var2=np.array([[1],[2],[3]])
print(var2.shape)
print(var1+var2)  #here error because we can not add 1*4 array with 1*3 array


(4,)
(3, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [ ]:
#indexing and slicing 
#indexing of a numpy array
"""
[1 2 3 4]
0 1 2 3 ->indexing og 1 D 
-4 -3 -2 -1->indexing of 1 D


2d
  0 1
[[1 2]->0
 [3 4]]->1


3d 
    0  1 2
[[ [1 2 3]->0
  [4 5 6]->1 ]->0
  [ [1 2 3]
  [1 2 3] ]->1]
"""


In [50]:
import numpy as np

#1 dimension array
#indexing is 0,1,2,3,4,5,6,7,8...
a=np.array([1,2,3,4,5,6,7,8,9,10])
 #                    .....3-2-1-
print(a[5])
print(a[-5])
print(a[-1])

#2 dimension array
twod_array=np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(twod_array.ndim)
print(f"Getting value {twod_array[0,7]}")

#3 dimension array
var3=np.array([[[1,2],[3,4]]])
print(var3.ndim)
print(var3[0,1,1]) #index for value 4


#slicing
list_nums=np.array([1,2,3,4,5,6,7,8,9,10])
#start:stop:jump
print(list_nums[4:8:2]) #4 se 8 with 2 increased.

print(list_nums[2:]) #from 3 to end.

print(list_nums[:7]) #from start to 7.


print(list_nums[::2]) #from start to end with 2 increased.


#2 dimension array slicing
#[x,y:step] -> x is row and y is column
array_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_2d[0,1:])

6
6
10
2
Getting value 8
3
4
[5 7]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[1 3 5 7 9]
[2 3 4 5]


In [60]:
#numpy iteration
import numpy as np

arr1=np.array([1,2,3,4,5])

for i in arr1:
    print(i)

print() #for empty line
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in arr2:
    for j in i:
        print(j)

print(f"<------------------>")
#for 3d array
threedim_array=np.array([[[1,2,3,4,5],
                          [6,7,8,9,10]]])
for i in threedim_array:
    for j in i:
        for k in j:
            print(k)


#nditer() ->used for iteration without for loop
print(f"ITERATING WITHOUT USING FOR LOOP")
for h in np.nditer(threedim_array):
    print(h)


#if we want data and index value too we use ndenumerate() method
for u,v in np.ndenumerate(threedim_array):
    print(u,v)

1
2
3
4
5

1
2
3
4
5
6
7
8
9
10
<------------------>
1
2
3
4
5
6
7
8
9
10
ITERATING WITHOUT USING FOR LOOP
1
2
3
4
5
6
7
8
9
10
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10


In [1]:
#copy and view
#both are used to copy elements
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10])
copy_array=a.copy()
print(a)
print(copy_array)


#view()
b=np.array([5,4,7,8,9,2,0])
b_view=b.view()
print(b)
print(b_view)

#copy()-> new array. changes in new array does not effect original array
#view()->overrides the array. so changes will be shown in both

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[5 4 7 8 9 2 0]
[5 4 7 8 9 2 0]


In [13]:
#joining and spliting arrays
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

merged=np.concatenate((a,b))
print(merged)



#2d array
var=np.array([[1,2,3],[4,5,6]])
var2=np.array([[7,8,9],[10,11,12]])

#here we need to tell axis 
new=np.concatenate((var,var2),axis=1) 
new2=np.concatenate((var,var2),axis=0)
print(new)
print(new2)


#merging using stack() function
new_arr=np.stack((var,var2))
#to merge about row we can use hstack()
#to merge about column we can use vstack()
#to mergee about height we use dstack()

print("The array merged using stack() function is ")
print(new_arr)

print("merge about row")
new_ar_row=np.hstack((var,var2)) #hstakc->horizontally
print(new_ar_row)


print("Merge about column")
new_ar_col=np.vstack((var,var2))  #vstack-> vertically
print(new_ar_col)

print("Merge about height")
new_ar_ht=np.dstack((var,var2))
print(new_ar_ht)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
The array merged using stack() function is 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
merge about row
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Merge about column
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Merge about height
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [27]:
#SPLITTING OF ARRAYS
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10])
splitted=np.array_split(a,2)  #split array a in 2 arrays 
print(splitted)


#2d array
twod_arr=np.array([[1,2,3],[4,5,6]])
splitted_twod=np.array_split(twod_arr,2)
print(splitted_twod)


#splitting about axis
a2=np.array([1,2,3,4,5,6,7,8,9,10])
splitted_about_axis=np.array_split(a2,3)
print(splitted_about_axis)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [47]:
#Functions in numpy arrays ->search sort filter....etc.
import numpy as np

h=np.array([1,2,3,14,15,16,17,18,19,10,11,12,13,14,15,16,17,18,19,20])


#we want to search where element is present in array
x=np.where(h==14)
print(x) #we got output [3,13] -> 14 is present at index 3 and 13.

#To search a sorted array
sorted=np.array([10,20,30,40,50,60,70,80,90,100])
searched=np.searchsorted(sorted,45) #if we add 45 in sorted array where it should be placed is told by this function
print(searched)


#how to sort array

u=np.array([4,8,7,2,9,1,10,12,12])
sort_array=np.sort(u)
print(sort_array)

alphabets=np.array(['A','G','B','f','p','b','V'])
print(np.sort(alphabets))

#sorting a 2d array
sort_2d=np.array([[1,2,5,7,8,2],[14,10,1,5,26,28]]) #2d arrays sorting means sort each row accordingly
print(np.sort(sort_2d))

#filtering of array-> it creates a new array with all the filtered elements
aww=np.array([1,2,5,8,9,96,32])
f=[True,False,False,True,True,False,True] #we will filter based on this array. Jin indexes pe here true only those indexes will be filtered out
new_array=aww[f]
print(new_array)

#shuffle function
arr_to_be_shuffled=np.array([1,2,3,4,5,6,7,8,9,10])
np.random.shuffle(arr_to_be_shuffled)
print(arr_to_be_shuffled)

#unique
unique=np.array([1,1,1,1,2,2,2,3,3,3,3,3,3,4,4,5])
print(np.unique(unique)) #removes repetitions

#resize
gr=np.array([1,2,3,4,5,6])
resized=np.resize(gr,(2,3)) #resized 1d array to 2*3 array
print(resized)

#flatten->2d to 1d 
array_to_be_flattened=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_to_be_flattened.flatten())

#to flatten about some particular axis
"""
C-> ROW MAJOR
F-> COLUMN MAJOR
K-> TO FLATTEN IN ORDER THE ELEMENTS OCCUR IN MEMORY
DEFAULT MODE IS C"""

print(array_to_be_flattened.flatten(order="F"))
print(np.ravel(array_to_be_flattened))

(array([ 3, 13], dtype=int64),)
4
[ 1  2  4  7  8  9 10 12 12]
['A' 'B' 'G' 'V' 'b' 'f' 'p']
[[ 1  2  2  5  7  8]
 [ 1  5 10 14 26 28]]
[ 1  8  9 32]
[ 8  9  1  5  4  2 10  3  6  7]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  6  2  7  3  8  4  9  5 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [65]:
#insertion and deletion
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])

v=np.insert(arr,4,40) #insert 40 at index 4
print(v)

#we also insert at multiple positions insert 40 at 4 and 9 positions
p=np.insert(arr,(4,9),40)
print(p)

#inserting at 2D arrays
twod_arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
r=np.insert(twod_arr,2,6,axis=1)
print(r)


#append()-> add element at end
u=np.array([1,2,3,4,5,6,7,8,9])
v=np.append(u,10)
print(v)

#delete()-> delete a data at given position
e=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.delete(e,5) #(array,index)
print(b)

[ 1  2  3  4 40  5  6  7  8  9 10]
[ 1  2  3  4 40  5  6  7  8  9 40 10]
[[ 1  2  6  3  4  5  6]
 [ 7  8  6  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  7  8  9 10]


In [84]:
#MATRICES IN NUMPY
"""
[[123]
 [456]
 [789]]
 3*3 matrix
 main diff is  b/w multiplication in matrix and array
 """
import numpy as np
matrix1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(type(matrix1))

arr1=np.array([[1,2,3],[4,5,6]])
print(type(arr1))

"""
array multiplication only first value with first value
matrix   " mai first row woth first column ........
"""
#for matrix multiplication we use dot ()
print(matrix1.dot(matrix2))


#matrix functions in numpy
#like inverse etc.
"""
transpose
swapaxes
inverse
power
determinate
"""

mat=np.matrix([[1,2,3],[4,5,6]])
print(np.transpose(mat))

#swapaxes
print(np.swapaxes(mat,0,1))

mat2=np.matrix([[1,2],[3,4]])
print(np.swapaxes(mat2,0,1))

#Inverse
print(f"inverse is {np.linalg.inv(mat2)}")


#power of matrix
#A2=A*A
print(f"Power is {np.linalg.matrix_power(mat2,2)}")


print(f"{np.linalg.matrix_power(mat2,0)}") #identity matrix


#determinant 

print(f"the determinant of matrix is {np.linalg.det(mat2)}")



<class 'numpy.matrix'>
<class 'numpy.ndarray'>
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 3]
 [2 4]]
inverse is [[-2.   1. ]
 [ 1.5 -0.5]]
Power is [[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
the determinant of matrix is -2.0000000000000004
